export const SWITCH_ONBOARDING = 'SWITCH_ONBOARDING';
export const SWITCH_INFOMODAL = 'SWITCH_INFOMODAL';
export const SWITCH_LOG = 'SWITCH_LOG';
export const SET_LOG_USER = 'SET_LOG_USER';
export const SET_USER_PROFILES='SET_USER_PROFILES';
export const SET_COMPANIES_PROFILES='SET_COMPANIES_PROFILES';
export const SET_SERVER_RESPONSE='SET_SERVER_RESPONSE';
export const SET_RESET_ANALYSIS='SET_RESET_ANALYSIS';
export const SET_GLOBAL_LOADING='SET_GLOBAL_LOADING';
export const SET_ERRORS='SET_LOADING';
export const SET_NOTIFICATIONS='SET_NOTIFICATIONS';


export const SET_COMPANIES='SET_COMPANIES';
export const SET_COMPANY = 'SET_COMPANY';
export const SET_USERS='SET_USERS';
export const SET_USER='SET_USER';